# Generated by Django 2.2.6 on 2019-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('sex', models.CharField(default='M', max_length=1)),
                ('icd10', models.CharField(max_length=20)),
            ],
        ),
    ]
